CREATE TABLE `option_quotes` (
	`snapshot_ms` integer NOT NULL,
	`slot` text NOT NULL,
	`index_id` text NOT NULL,
	`expiry` text NOT NULL,
	`expiry_kind` text NOT NULL,
	`strike` real NOT NULL,
	`option_type` text NOT NULL,
	`trading_symbol` text NOT NULL,
	`lot_size` integer NOT NULL,
	`bid` real,
	`ask` real,
	`bid_qty` integer,
	`ask_qty` integer,
	`ltp` real,
	`last_trade_ms` integer,
	`volume` integer,
	`oi` integer,
	`depth` text,
	`spot` real,
	`fetched_ms` integer NOT NULL,
	`source` text NOT NULL,
	`schema_v` integer NOT NULL,
	PRIMARY KEY(`snapshot_ms`, `trading_symbol`)
);
